# Generated by Django 5.1.1 on 2024-10-12 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_delete_student_remove_course_name_course_course_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='s', max_length=255),
        ),
    ]
