# Generated by Django 5.1.1 on 2024-10-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('exam_date', models.DateField()),
            ],
        ),
    ]
